language: node_js
node_js:
  - node

before_install:
  - npm install -g npm@6
  - npm install -g codecov

install:
  - npm ci

script:
  - npm run test:ci

after_script:
  - codecov

before_deploy:
  - npm run build
  - sed -i 's/href="\/"/href="\/web\/"/g' ${TRAVIS_BUILD_DIR}/build/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: gh-pages
  on:
    branch: master
