export const capeCod = '#3E4444'
export const alabaster = '#E7E7E7'
export const shark = '#1a1c21'
export const mountainMeadow = '#26A69A'
export const silver = '#bdc3c7'
export const melrose = '#A29BFE'
export const manatee = '#9C9C9E'
export const gossamer = '#03a37e'
