export const Routes = {
  upcoming: '/',
  following: '/following',
  popular: '/popular',
  history: '/history',
  settings: '/settings',
  search: '/search',
  show: '/show/:id/:tvdb?',
  login: '/login/:type?',
  authAction: '/auth-action',
  about: '/about',
  privacy: '/privacy',
  tos: '/tos',
  kodi: '/kodi',
  plex: '/plex',
  googlehome: '/googlehome',
  faq: '/faq',
  contact: '/contact',
  landingPage: '/landingpage',
  forgotPassword: '/forgotpassword',
} as const
